export const DEFAULT_QUESTIONS_DATA = [
  { q: "Ai là tác giả của tác phẩm 'Truyện Kiều'?", o: ["Nguyễn Trãi", "Nguyễn Du", "Chu Văn An", "Hồ Xuân Hương"], a: 1 },
  { q: "Đỉnh núi nào được mệnh danh là 'Nóc nhà của Đông Dương'?", o: ["Fansipan", "Mẫu Sơn", "Bạch Mã", "Tây Côn Lĩnh"], a: 0 },
  { q: "Hành tinh nào gần Mặt Trời nhất?", o: ["Sao Kim", "Sao Hỏa", "Sao Thủy", "Sao Thổ"], a: 2 },
  { q: "Sông nào dài nhất thế giới?", o: ["Sông Amazon", "Sông Nile", "Sông Mê Kông", "Sông Trường Giang"], a: 1 },
  { q: "Quốc gia nào có diện tích lớn nhất thế giới?", o: ["Mỹ", "Trung Quốc", "Nga", "Canada"], a: 2 },
  { q: "Ai là người đầu tiên đặt chân lên Mặt Trăng?", o: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Michael Collins"], a: 1 },
  { q: "Nguyên tố hóa học nào có ký hiệu là 'O'?", o: ["Vàng", "Sắt", "Oxy", "Bạc"], a: 2 },
  { q: "Thủ đô của nước Pháp là gì?", o: ["Berlin", "London", "Madrid", "Paris"], a: 3 },
  { q: "Đại dương nào lớn nhất thế giới?", o: ["Đại Tây Dương", "Ấn Độ Dương", "Thái Bình Dương", "Bắc Băng Dương"], a: 2 },
  { q: "Bác Hồ đọc bản Tuyên ngôn Độc lập vào ngày tháng năm nào?", o: ["02/09/1945", "19/05/1890", "30/04/1975", "22/12/1944"], a: 0 },
  { q: "Loài vật nào được coi là 'Chúa tể sơn lâm'?", o: ["Voi", "Sư tử", "Hổ", "Báo"], a: 2 },
  { q: "Số Pi xấp xỉ bằng bao nhiêu?", o: ["3.12", "3.14", "3.16", "3.18"], a: 1 },
  { q: "Họa sĩ nào là tác giả của bức tranh 'Mona Lisa'?", o: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], a: 2 },
  { q: "Đất nước nào được mệnh danh là 'Xứ sở hoa anh đào'?", o: ["Hàn Quốc", "Trung Quốc", "Nhật Bản", "Thái Lan"], a: 2 },
  { q: "Đơn vị đo cường độ dòng điện là gì?", o: ["Volt", "Watt", "Ohm", "Ampe"], a: 3 },
  { q: "Thành phố nào là thủ đô của Việt Nam?", o: ["Hà Nội", "TP. Hồ Chí Minh", "Đà Nẵng", "Huế"], a: 0 },
  { q: "Lễ hội Đền Hùng được tổ chức vào ngày nào âm lịch?", o: ["10/01", "10/03", "15/08", "01/01"], a: 1 },
  { q: "Kim loại nào dẫn điện tốt nhất?", o: ["Vàng", "Đồng", "Bạc", "Nhôm"], a: 2 },
  { q: "Cơ quan nào trong cơ thể con người có chức năng lọc máu?", o: ["Tim", "Phổi", "Gan", "Thận"], a: 3 },
  { q: "Ai là người phát minh ra bóng đèn sợi đốt?", o: ["Isaac Newton", "Albert Einstein", "Thomas Edison", "Nikola Tesla"], a: 2 },
  { q: "Đảo lớn nhất thế giới là đảo nào?", o: ["Greenland", "Madagascar", "New Guinea", "Borneo"], a: 0 },
  { q: "Loài chim nào không biết bay?", o: ["Đại bàng", "Đà điểu", "Hải âu", "Vẹt"], a: 1 },
  { q: "Đồng tiền chung của Liên minh Châu Âu là gì?", o: ["Dollar", "Yên", "Euro", "Bảng"], a: 2 },
  { q: "Tác phẩm 'Dế Mèn phiêu lưu ký' là của nhà văn nào?", o: ["Tô Hoài", "Nam Cao", "Thạch Lam", "Ngô Tất Tố"], a: 0 },
  { q: "Châu lục nào lạnh nhất thế giới?", o: ["Châu Á", "Châu Âu", "Châu Nam Cực", "Châu Phi"], a: 2 },
  { q: "Vitamin nào có nhiều trong cam, chanh?", o: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], a: 2 },
  { q: "Môn thể thao nào được gọi là 'Môn thể thao vua'?", o: ["Bóng rổ", "Bóng đá", "Quần vợt", "Cầu lông"], a: 1 },
  { q: "Tháp Eiffel nằm ở thành phố nào?", o: ["Rome", "Paris", "New York", "Tokyo"], a: 1 },
  { q: "Động vật nào lớn nhất hành tinh hiện nay?", o: ["Voi châu Phi", "Cá voi xanh", "Khủng long", "Hươu cao cổ"], a: 1 },
  { q: "Nước nào có dân số đông nhất thế giới hiện nay (2024)?", o: ["Trung Quốc", "Mỹ", "Ấn Độ", "Indonesia"], a: 2 },
  { q: "Cầu thủ nào giành được nhiều Quả bóng vàng nhất lịch sử?", o: ["Cristiano Ronaldo", "Lionel Messi", "Pele", "Maradona"], a: 1 },
  { q: "Vạn Lý Trường Thành nằm ở quốc gia nào?", o: ["Nhật Bản", "Hàn Quốc", "Trung Quốc", "Mông Cổ"], a: 2 },
  { q: "Loài cây nào tượng trưng cho quân tử trong văn hóa Á Đông?", o: ["Cây Đa", "Cây Tre", "Cây Thông", "Cây Mai"], a: 1 },
  { q: "Khí nào chiếm tỉ lệ lớn nhất trong không khí?", o: ["Oxy", "Nitơ", "Cacbonic", "Hydro"], a: 1 },
  { q: "Ai là người tìm ra châu Mỹ?", o: ["Vasco da Gama", "Christopher Columbus", "Magellan", "Marco Polo"], a: 1 },
  { q: "Đơn vị đo công suất là gì?", o: ["Joule", "Watt", "Newton", "Pascal"], a: 1 },
  { q: "Hành tinh nào được gọi là 'Hành tinh đỏ'?", o: ["Sao Kim", "Sao Hỏa", "Sao Mộc", "Sao Thổ"], a: 1 },
  { q: "Đàn bầu là nhạc cụ có mấy dây?", o: ["1 dây", "2 dây", "3 dây", "4 dây"], a: 0 },
  { q: "Thành phố nào được gọi là 'Thành phố ngàn hoa'?", o: ["Đà Lạt", "Sa Pa", "Nha Trang", "Vũng Tàu"], a: 0 },
  { q: "Tác giả của bộ truyện 'Harry Potter' là ai?", o: ["J.R.R. Tolkien", "J.K. Rowling", "Stephen King", "George R.R. Martin"], a: 1 },
  { q: "Ngọn núi cao nhất thế giới là gì?", o: ["Everest", "K2", "Lhotse", "Makalu"], a: 0 },
  { q: "Kim tự tháp Giza nằm ở đâu?", o: ["Hy Lạp", "Ý", "Ai Cập", "Mexico"], a: 2 },
  { q: "Loài cá nào là cá nhanh nhất đại dương?", o: ["Cá mập", "Cá buồm", "Cá heo", "Cá ngừ"], a: 1 },
  { q: "Đất nước nào có nhiều đảo nhất thế giới?", o: ["Indonesia", "Philippines", "Thụy Điển", "Canada"], a: 2 },
  { q: "Ai là người phát minh ra điện thoại?", o: ["Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi", "Benjamin Franklin"], a: 0 },
  { q: "Màu sắc nào là sự kết hợp của màu xanh dương và màu vàng?", o: ["Màu cam", "Màu tím", "Màu xanh lá cây", "Màu hồng"], a: 2 },
  { q: "Quốc gia nào nhỏ nhất thế giới về diện tích?", o: ["Monaco", "Vatican", "San Marino", "Nauru"], a: 1 },
  { q: "Tên gọi khác của Sài Gòn là gì?", o: ["Hà Nội", "Đà Nẵng", "Thành phố Hồ Chí Minh", "Cần Thơ"], a: 2 },
  { q: "Động vật nào có cổ dài nhất?", o: ["Đà điểu", "Hươu cao cổ", "Rắn", "Thiên nga"], a: 1 },
  { q: "Năm nhuận có bao nhiêu ngày?", o: ["364 ngày", "365 ngày", "366 ngày", "367 ngày"], a: 2 },
  { q: "Đơn vị đo tần số là gì?", o: ["Hertz", "Decibel", "Lux", "Tesla"], a: 0 },
  { q: "Ai là người sáng lập ra mạng xã hội Facebook?", o: ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Elon Musk"], a: 2 },
  { q: "Đất nước nào được gọi là 'Xứ sở chùa vàng'?", o: ["Lào", "Campuchia", "Thái Lan", "Myanmar"], a: 2 },
  { q: "Loài thú nào duy nhất biết bay?", o: ["Sóc bay", "Dơi", "Chim cánh cụt", "Gà"], a: 1 },
  { q: "Thủ đô của Nhật Bản là gì?", o: ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], a: 2 },
  { q: "Đơn vị đo áp suất là gì?", o: ["Pascal", "Newton", "Joule", "Watt"], a: 0 },
  { q: "Tác phẩm 'Lão Hạc' là của nhà văn nào?", o: ["Ngô Tất Tố", "Nam Cao", "Nguyễn Công Hoan", "Vũ Trọng Phụng"], a: 1 },
  { q: "Hệ mặt trời có bao nhiêu hành tinh chính thức?", o: ["7", "8", "9", "10"], a: 1 },
  { q: "Môn võ nào là quốc võ của Nhật Bản?", o: ["Karate", "Judo", "Sumo", "Kendo"], a: 2 },
  { q: "Ai là người phát minh ra bảng tuần hoàn các nguyên tố hóa học?", o: ["Mendeleev", "Dalton", "Curie", "Nobel"], a: 0 }
];
